name: Content Collector

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      run: python collect.py

    - name: Validate file
      run: |
        if [ ! -f "top50_valid_content.txt" ]; then
          echo "::error::文件生成失败！"
          exit 1
        fi

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add top50_valid_content.txt
        
        # 智能提交判断
        if [ -z "$(git status --porcelain)" ]; then
          echo "没有变更需要提交"
        else
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
          git push origin main
        fi